<?php

require_once 'vendor/autoload.php';

$holland = new Country('Holland', [
    new Airport('AMS', true),
    new Airport('MST'),
    new Airport('EIN'),
    new Airport('RTM'),
]);
$belgium = new Country('Belgium', [
    new Airport('BRU', true),
    new Airport('CRL', true),
]);
$ireland = new Country('Ireland', [
    new Airport('ORK'),
    new Airport('DUB', true),
    new Airport('NOC'),
    new Airport('KIR'),
    new Airport('SNN'),
    new Airport('CFN'),
]);
$denmark = new Country('Denmark', [
    new Airport('AAR'),
    new Airport('BLL'),
    new Airport('CPH', true),
    new Airport('RNN'),
    new Airport('AAL'),
]);
$spain = new Country('Spain', [
    new Airport('FUE'),
    new Airport('SPC'),
    new Airport('LPA'),
    new Airport('ACE'),
    new Airport('TFS'),
    new Airport('TFN'),
    new Airport('ALC'),
    new Airport('LEI'),
    new Airport('OVD'),
    new Airport('BIO'),
    new Airport('BCN'),
    new Airport('LCG'),
    new Airport('GRO'),
    new Airport('GRX'),
    new Airport('IBZ'),
    new Airport('XRY'),
    new Airport('MAD', true),
    new Airport('AGP'),
    new Airport('MAH'),
    new Airport('PNA'),
    new Airport('RMU'),
    new Airport('REU'),
    new Airport('SLM'),
    new Airport('EAS'),
    new Airport('SCQ'),
    new Airport('VLC'),
    new Airport('VLL'),
    new Airport('VIT'),
    new Airport('VGO'),
    new Airport('SDR'),
    new Airport('ZAZ'),
    new Airport('SVQ'),
    new Airport('PMI'),
    new Airport('RJL'),
    new Airport('LEN'),
    new Airport('CDT'),
]);
$france = new Country('France', [
    new Airport('BOD'),
    new Airport('EGC'),
    new Airport('PIS'),
    new Airport('LIG'),
    new Airport('TLS'),
    new Airport('PUF'),
    new Airport('LDE'),
    new Airport('BVE'),
    new Airport('BIQ'),
    new Airport('DLE'),
    new Airport('BIA'),
    new Airport('CLY'),
    new Airport('FSC'),
    new Airport('AJA'),
    new Airport('CFE'),
    new Airport('LYS'),
    new Airport('GNB'),
    new Airport('CCF'),
    new Airport('MRS'),
    new Airport('NCE'),
    new Airport('PGF'),
    new Airport('MPL'),
    new Airport('BZR'),
    new Airport('BVA', true),
    new Airport('XCR', true),
    new Airport('TUF'),
    new Airport('CDG', true),
    new Airport('ORY', true),
    new Airport('LIL'),
    new Airport('BES'),
    new Airport('DOL'),
    new Airport('CFR'),
    new Airport('RNS'),
    new Airport('NTE'),
    new Airport('MLH'),
    new Airport('SXB'),
    new Airport('TLN'),
    new Airport('FNI'),
    new Airport('LRH'),
]);
$italy = new Country('Italy', [
    new Airport('CRV'),
    new Airport('BRI'),
    new Airport('PSR'),
    new Airport('BDS'),
    new Airport('SUF'),
    new Airport('CTA'),
    new Airport('LMP'),
    new Airport('PNL'),
    new Airport('PMO'),
    new Airport('REG'),
    new Airport('TPS'),
    new Airport('AHO'),
    new Airport('CAG'),
    new Airport('OLB'),
    new Airport('MXP'),
    new Airport('BGY'),
    new Airport('TRN'),
    new Airport('GOA'),
    new Airport('LIN'),
    new Airport('PMF'),
    new Airport('CUF'),
    new Airport('BLQ'),
    new Airport('TSF'),
    new Airport('FRL'),
    new Airport('TRS'),
    new Airport('RMI'),
    new Airport('VRN'),
    new Airport('VCE'),
    new Airport('CIA', true),
    new Airport('FCO', true),
    new Airport('NAP'),
    new Airport('PSA'),
    new Airport('FLR'),
    new Airport('PEG'),
    new Airport('AOI'),
    new Airport('CIY'),
]);
$portugal = new Country('Portugal', [
    new Airport('FAO'),
    new Airport('TER'),
    new Airport('PDL'),
    new Airport('OPO'),
    new Airport('PXO'),
    new Airport('LIS', true),
    new Airport('FNC'),
]);
$cyprus = new Country('Cyprus', [
    new Airport('LCA'),
    new Airport('PFO'),
    new Airport('ECN'),
]);
$morocco = new Country('Morocco', [
    new Airport('AGA'),
    new Airport('FEZ'),
    new Airport('OUD'),
    new Airport('RBA', true),
    new Airport('CMN'),
    new Airport('RAK'),
    new Airport('OZZ'),
    new Airport('AHU'),
    new Airport('TTU'),
    new Airport('TNG'),
    new Airport('ESU'),
    new Airport('NDR'),
    new Airport('GLN'),
]);
$turkey = new Country('Turkey', [
    new Airport('ESB', true),
    new Airport('ADA'),
    new Airport('AYT'),
    new Airport('GZT'),
    new Airport('KYA'),
    new Airport('VAS'),
    new Airport('MLX'),
    new Airport('ASR'),
    new Airport('DNZ'),
    new Airport('IST'),
    new Airport('ADB'),
    new Airport('IGD'),
    new Airport('DLM'),
    new Airport('EZS'),
    new Airport('DIY'),
    new Airport('ERC'),
    new Airport('ERZ'),
    new Airport('TZX'),
    new Airport('VAN'),
    new Airport('BAL'),
    new Airport('BJV'),
    new Airport('SAW'),
    new Airport('KSY'),
    new Airport('EDO'),
    new Airport('SZF'),
    new Airport('MQM'),
    new Airport('AOE'),
    new Airport('MSR'),
    new Airport('TEQ'),
    new Airport('HTY'),
    new Airport('GZP'),
    new Airport('KZR'),
    new Airport('GNY'),
    new Airport('ONQ'),
    new Airport('OGU'),
    new Airport('BGG'),
]);
$usa = new Country('USA', [
    new Airport('BOS'),
    new Airport('PHX'),
    new Airport('SFO'),
    new Airport('LAX'),
    new Airport('CLE'),
    new Airport('EWR'),
    new Airport('FLL'),
    new Airport('MIA'),
    new Airport('SEA'),
    new Airport('SWF'),
    new Airport('IAD'),
    new Airport('PDX'),
    new Airport('PHL'),
    new Airport('ANC'),
    new Airport('JFK'),
    new Airport('BDL'),
    new Airport('ORD'),
    new Airport('FAI'),
    new Airport('BWI'),
    new Airport('MSP'),
    new Airport('LAS'),
    new Airport('MCO'),
]);
$island = new Country('Island', [
    new Airport('AEY'),
    new Airport('EGS'),
    new Airport('KEF', true),
]);

$countries = [
//    $holland,
//    $belgium,
    $ireland,
//    $denmark,
    $spain,
//    $france,
    $italy,
    $portugal,
//    $cyprus,
    $turkey,
    $morocco,
    $island,
//    $usa,
//	new Country('Hungary', [
//		new Airport('Budapest [BUD]', true)
//	]),
//	new Country('Romania', [
//		new Airport('Bucharest [OTP] (+BBU)', true)
//	]),
//	new Country('Serbia', [
//		new Airport('Belgrade [BEG]', true)
//	]),
//	new Country('Finland', [
//		new Airport('Helsinki [HEL]', true)
//	]),
//	new Country('Georgia', [
//		new Airport('Tbilisi [TBS]', true),
//		new Airport('Kutaisi [KUT]'),
//	])
];
$onlyCapitals = false;


$countriesProvider = new CountriesProvider($countries);

echo "START";
$config = [
    'onlyCapitals' => false,
    'maxPrice' => 400,
    'minStayPeriod' => 3,
    'maxStayPeriod' => 7,
    'from' => '01.03.2023',
    'to' => '30.04.2023',
    'onlyWeekends' => false,
    'exceptionDays' => [
        // Zjazdy
        '03.12.2022 00:00:00',
        '04.12.2022 00:00:00',
        '17.12.2022 00:00:00',
        '18.12.2022 00:00:00',
        '14.01.2023 00:00:00',
        '15.01.2023 00:00:00',
        '28.01.2023 00:00:00',
        '29.01.2023 00:00:00',
        '11.02.2023 00:00:00',
        '12.02.2023 00:00:00',
        '11.03.2023 00:00:00',
        '12.03.2023 00:00:00',
        '25.03.2023 00:00:00',
        '26.03.2023 00:00:00',
        '15.04.2023 00:00:00',
        '16.04.2023 00:00:00',
        '29.04.2023 00:00:00',
        '30.04.2023 00:00:00',
        '13.05.2023 00:00:00',
        '14.05.2023 00:00:00',
        '27.05.2023 00:00:00',
        '28.05.2023 00:00:00',
        '10.06.2023 00:00:00',
        '11.06.2023 00:00:00',
        '24.06.2023 00:00:00',
        '25.06.2023 00:00:00',

        // Kursy
        '21.01.2023 00:00:00',
        '22.01.2023 00:00:00',
        '04.02.2023 00:00:00',
        '05.02.2023 00:00:00',
        '18.02.2023 00:00:00',
        '04.03.2023 00:00:00',
        '05.03.2023 00:00:00',
        '18.03.2023 00:00:00',
        '19.03.2023 00:00:00',
        '01.04.2023 00:00:00',
        '02.04.2023 00:00:00',
        '22.04.2023 00:00:00',
        '23.04.2023 00:00:00',
        '20.05.2023 00:00:00',
        '21.05.2023 00:00:00',
        '03.06.2023 00:00:00',
        '04.06.2023 00:00:00',
        '17.06.2023 00:00:00',
    ],
];
$azAir = new AzAir($countriesProvider->getCountries(), $config);
$azAir->run(true);
//(new Booking())->run();
echo "END";